using QuazarAPI.Networking.Data;
using nio2so.TSOTCP.City.TSO.Voltron.Serialization;
using nio2so.TSOTCP.City.TSO.Voltron.Util;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MiscUtil.Conversion;
using static nio2so.Data.Common.Serialization.Voltron.TSOVoltronSerializationAttributes;
using nio2so.Data.Common.Serialization.Voltron;
using nio2so.TSOTCP.City.TSO.Voltron.Struct;
using nio2so.TSOTCP.City.TSO.Voltron.PDU.Datablob.Structures;

namespace nio2so.TSOTCP.City.TSO.Voltron.PDU.Datablob
{
    public class TSOBroadcastDatablobPDUHeader : ITSOVoltronSpecializedPDUHeader
    {
        public TSOAriesIDStruct CurrentSessionID { get; set; }
        public ushort Arg1 { get; set; } = 0x4101;
        public uint MessageLength { get; set; }
        public TSO_PreAlpha_MasterConstantsTable SubMsgCLSID { get; set; }
        public TSOGenericDataBlobContent DataBlobContentObject { get; set; }
    }

    /// <summary>
    /// Basically packs and ships data of a defined format to the server with the intention to send it to all connected parties
    /// in the Room Server
    /// <para/>As a sidenote (not like anyone reads these but me any way) why is everything called a blob? idk me, why don't you ask them?
    /// well i tried but this was made 20 years ago. why am i even doing this?
    /// </summary>    
    [TSOVoltronPDU(TSO_PreAlpha_VoltronPacketTypes.BROADCAST_DATABLOB_PDU)]
    public class TSOBroadcastDatablobPacket : TSOVoltronSpecializedPacket<TSOVoltronBroadcastDatablobPDUField, TSOBroadcastDatablobPDUHeader>, 
        ITSOVoltronAriesMasterIDStructure, ITSODataBlobPDU
    {
        private const uint MESSAGELENGTH_TO_BODY = sizeof(uint);

        public override ushort VoltronPacketType => (ushort)TSO_PreAlpha_VoltronPacketTypes.BROADCAST_DATABLOB_PDU;
        protected override TSOBroadcastDatablobPDUHeader Header { get; } = new();

        public TSOAriesIDStruct CurrentSessionID
        {
            get => Header.CurrentSessionID;
            set => Header.CurrentSessionID = value;
        }
        public ushort Arg1
        {
            get => Header.Arg1;
            set => Header.Arg1 = value;
        }
        [TSOVoltronDistanceToEnd] public uint MessageLength
        {
            get => Header.MessageLength;
            set => Header.MessageLength = value;
        }
        public TSO_PreAlpha_MasterConstantsTable SubMsgCLSID
        {
            get => Header.SubMsgCLSID;
            set => Header.SubMsgCLSID = value;
        }
        public TSOGenericDataBlobContent DataBlobContentObject
        {
            get => Header.DataBlobContentObject;
            set
            {
                Header.DataBlobContentObject = value;
                Header.DataBlobContentObject?.SetCLSID(SubMsgCLSID); // used for ToString() mainly
            }
        }

        /// <summary>
        /// This is the default, parameterless constuctor.
        /// <para/>You should use this in two scenarios: Using reflection to instantiate an instance of a type of 
        /// <see cref="TSODBRequestWrapper"/> OR writing a <see cref="TSODBRequestWrapper"/> that has a <see cref="TSODBRequestWrapper.kMSGID"/>
        /// that is: <see cref="TSO_PreAlpha_kMSGs.kDBServiceRequestMsg"/> as this is sent from the Client and the structure is not generated by the
        /// nio2so <see cref="TSOVoltronPacket"/> API        
        /// </summary>
        public TSOBroadcastDatablobPacket() : base()
        {
            MakeBodyFromProperties();
        }

        /// <summary>
        /// Creates a new <see cref="TSODBRequestWrapper"/> PDU where the argument list has been
        /// simplified to automate more of the properties that can be confusing otherwise.
        /// </summary>
        /// <param name="StructCLSID"></param>
        /// <param name="kMSG_ID"></param>
        /// <param name="DBAction"></param>
        /// <param name="Header"></param>
        /// <param name="Payload"></param>
        public TSOBroadcastDatablobPacket(TSO_PreAlpha_MasterConstantsTable SubMsgCLSID, 
            ITSODataBlobContentObject? ContentObject = default,
            uint MessageLength = 0xFFFFFFFF)
        {
            this.SubMsgCLSID = SubMsgCLSID;
            DataBlobContentObject = new TSOGenericDataBlobContent(ContentObject);

            this.MessageLength = MessageLength;
            MakeBodyFromProperties();
        }
        public TSOBroadcastDatablobPacket(TSO_PreAlpha_MasterConstantsTable SubMsgCLSID, byte[] ContentBytes)
            : this(SubMsgCLSID)
        {
            DataBlobContentObject = new TSOGenericDataBlobContent(ContentBytes);
            MakeBodyFromProperties();
        }
        /// <summary>
        /// Copy constructor for creating a <see cref="TSOBroadcastDatablobPacket"/> from a <see cref="TSOTransmitDataBlobPacket"/>
        /// </summary>
        /// <param name="transmitPDU"></param>
        public TSOBroadcastDatablobPacket(TSOTransmitDataBlobPacket transmitPDU) : 
            this(transmitPDU.SubMsgCLSID, transmitPDU.DataBlobContentObject.ContentBytes)
        {
            CurrentSessionID = transmitPDU.CurrentSessionID;
            Arg1 = transmitPDU.Arg1;

            MakeBodyFromProperties();
        }

        /// <summary>
        /// Will read from the point just after the Size of the <see cref="TSOVoltronPacket"/> (0x80...) 2 strings, then a ushort, then read the size.
        /// </summary>
        /// <param name="BodyStream"></param>
        /// <returns></returns>
        public static uint ReadSpecializedPDUBodyLengthFromHeader(Stream BodyStream) => ReadSpecializedPDUHeader(BodyStream).MessageLength;

        /// <summary>
        /// Will read from the point just after the Size of the <see cref="TSOVoltronPacket"/> (0x80...) the <see cref="TSODBWrapperPDUHeader"/>
        /// </summary>
        /// <param name="BodyStream"></param>
        /// <returns></returns>
        public static TSOBroadcastDatablobPDUHeader ReadSpecializedPDUHeader(Stream BodyStream)
        {
            var startPosition = BodyStream.Position;
            var avatarID = TSOVoltronSerializerCore.ReadString(TSOVoltronValueTypes.Pascal, BodyStream);
            var avatarName = TSOVoltronSerializerCore.ReadString(TSOVoltronValueTypes.Pascal, BodyStream);
            ushort arg1 = BodyStream.ReadBodyUshort(Endianness.BigEndian);
            uint msgSize = BodyStream.ReadBodyDword(Endianness.BigEndian);
            uint actionCLSID = BodyStream.ReadBodyDword();
            BodyStream.Seek(startPosition, SeekOrigin.Begin);
            return new()
            {
                CurrentSessionID = new(avatarID, avatarName),
                Arg1 = arg1,
                MessageLength = msgSize,
                SubMsgCLSID = (TSO_PreAlpha_MasterConstantsTable)actionCLSID
            };
        }

        /// <summary>
        /// Use this function to extend the Body property to the <see cref="MessageLength"/> parameter.
        /// <para>See: <see cref="MessageLength"/> property for more info.</para>
        /// </summary>
        protected void FillPacketToAvailableSpace()
        {
            //TSOPacketFormat + Flags + TransID + SubMSgCLSID + CurrentBodySize
            long currentSize = BodyLength;
            int delta = (int)(Header.MessageLength - currentSize); // size diff
            if (delta <= 0) return; // yikes, not necessary to even do this.
            long newSize = delta + BodyLength;
            byte[] trash = new byte[delta];
            ReallocateBody((uint)newSize);
            EmplaceBodyAt((int)BodyLength - delta, trash);
            currentSize = (int)MESSAGELENGTH_TO_BODY + BodyLength;
            if (currentSize != MessageLength)
                throw new Exception("This should never happen.");
        }

        public override string ToShortString(string Arguments = "") => ToString();
        public override string ToString()
        {
            return $"{GetType().Name}::<{SubMsgCLSID}>({GetParameterListString()})";
        }
    }
}
