@nio2so.DataService.API_HostAddress = http://localhost:5231

# GET ACCOUNTS TEST
GET {{nio2so.DataService.API_HostAddress}}/api/avatars/1337/relationships?direction=outgoing
Accept: application/json
###
